[workspace]
resolver = "2"
members = [
    "satrs",
    "satrs-mib",
    "examples/obsw-std",
    "examples/types",
    "examples/client",
    "examples/minisim",
    "satrs-shared",
    "tmtc-utils",
    "examples/embedded-client",
    "examples/embedded-types",
]

exclude = [
    "examples/stm32f3-disco-rtic",
    "examples/stm32h7-nucleo-rtic",
]
