[package]
name = "stm32h7-nucleo-rtic"
edition = "2024"
version = "0.1.0"
default-run = "stm32h7-nucleo-rtic"

[lib]
harness = false

# needed for each integration test
[[test]]
name = "integration"
harness = false

[dependencies]
shared-embedded.workspace = true

cortex-m.workspace = true
cortex-m-rt.workspace = true
defmt.workspace = true
defmt-rtt.workspace = true
panic-probe.workspace = true
embedded-alloc.workspace = true
static_cell.workspace = true
rtic.workspace = true

embassy-stm32 = { workspace = true, features = ["memory-x", "time-driver-any"] }
embassy-time = { workspace = true, features = ["defmt-timestamp-uptime-ms", "generic-queue-16"] }
embassy-net.workspace = true

[dev-dependencies]
defmt-test.workspace = true
