[package]
name = "minisim-types"
version = "0.1.0"
edition = "2024"

[dependencies]
num_enum = { version = "0.7", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
tai-time = { version = "1", default-features = false, features = ["serde"] }
thiserror = { version = "2", default-features = false }
types = { path = "../types" }

[dev-dependencies]
postcard = { version = "1", features = ["alloc"] }
